// Generated by Melange
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Readline = require("readline");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

var rl = Readline.createInterface({
      input: process.stdin,
      output: process.stdout
    });

var lines = [];

function withAll(f) {
  rl.on("line", (function (data) {
          lines.push(data);
        }));
  rl.on("close", (function (param) {
          Curry._1(f, Belt_List.fromArray(lines));
        }));
}

exports.rl = rl;
exports.lines = lines;
exports.withAll = withAll;
/* rl Not a pure module */
