// Generated by Melange

import * as Curry from "melange/lib/es6/curry.js";
import * as Readline from "readline";
import * as Belt_List from "melange/lib/es6/belt_List.js";

var rl = Readline.createInterface({
      input: process.stdin,
      output: process.stdout
    });

var lines = [];

function withAll(f) {
  rl.on("line", (function (data) {
          lines.push(data);
        }));
  rl.on("close", (function (param) {
          Curry._1(f, Belt_List.fromArray(lines));
        }));
}

export {
  rl ,
  lines ,
  withAll ,
}
/* rl Not a pure module */
